name: Check & fix styling

on: [push]

jobs:
  phpcbf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - name: Install dependencies
        run: composer install --prefer-dist --no-suggest --no-progress

      - name: Detect & fix standard violations
        run: vendor/bin/phpcbf -n

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
